// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'game': string;
  'igdbLink': string;
  'igdbLinkIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
