// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'chip': string;
  'downloaded': string;
  'missing': string;
  'status': string;
  'strip': string;
  'unmonitored': string;
}
export const cssExports: CssExports;
export default cssExports;
