// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'folder': string;
  'game': string;
  'minimumAvailability': string;
  'monitor': string;
  'qualityProfile': string;
  'selectInput': string;
}
export const cssExports: CssExports;
export default cssExports;
