// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'igdbId': string;
  'steamAppId': string;
  'title': string;
  'year': string;
}
export const cssExports: CssExports;
export default cssExports;
