// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'blankpad': string;
  'card': string;
  'container': string;
  'grid': string;
  'hasFile': string;
  'info': string;
  'monitoredIcon': string;
  'noFile': string;
  'poster': string;
  'status': string;
  'title': string;
  'unmonitoredIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
