// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'columnDragSource': string;
  'columnPlaceholder': string;
  'columnPlaceholderAfter': string;
  'columnPlaceholderBefore': string;
  'isDraggingDown': string;
  'isDraggingUp': string;
}
export const cssExports: CssExports;
export default cssExports;
