// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addButton': string;
  'container': string;
  'info': string;
  'labelIcon': string;
  'modalFooter': string;
  'overview': string;
  'poster': string;
  'searchForMissingGameContainer': string;
  'searchForMissingGameInput': string;
  'searchForMissingGameLabel': string;
  'searchForMissingGameLabelContainer': string;
  'year': string;
}
export const cssExports: CssExports;
export default cssExports;
