// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'delayProfileDragSource': string;
  'delayProfilePlaceholder': string;
  'delayProfilePlaceholderAfter': string;
  'delayProfilePlaceholderBefore': string;
  'isDraggingUp': string;
  'isDraggingDown': string;
}
export const cssExports: CssExports;
export default cssExports;
