// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'danger': string;
  'game': string;
  'gameStatus': string;
  'gameTitle': string;
  'info': string;
  'primary': string;
  'purple': string;
  'queue': string;
  'success': string;
  'warning': string;
}
export const cssExports: CssExports;
export default cssExports;
