// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'blankpad': string;
  'container': string;
  'dlcBadge': string;
  'dlcCard': string;
  'dlcGrid': string;
  'dlcToolbar': string;
  'dlcInfo': string;
  'dlcPoster': string;
  'dlcStatus': string;
  'dlcTitle': string;
  'dlcTitleLink': string;
  'dlcType': string;
  'gameTypeBadge': string;
  'hasFile': string;
  'monitoredIcon': string;
  'noFile': string;
  'parentGameInfo': string;
  'parentLabel': string;
  'parentLink': string;
  'unmonitoredIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
