// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addButton': string;
  'addPlatformRootFolder': string;
  'path': string;
  'platform': string;
  'platformRootFoldersHeader': string;
}
export const cssExports: CssExports;
export default cssExports;
