// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'path': string;
  'platform': string;
  'platformRootFolder': string;
}
export const cssExports: CssExports;
export default cssExports;
